### ISSUE TITLE
Error adding an endpoint: Error when changing TabPy state: 'TABPY_STATE_PATH'

### ISSUE THREAD

**Issue by haupinzd** [tableau/TabPy#121]
Following the example here:

[(https://github.com/tableau/TabPy/blob/master/client.md#deploying-a-function)]

When I attempt to deploy the 'add' function, I get an error.

`
import tabpy_client

client = tabpy_client.Client('http://localhost:9004/')

def add(x,y):
    import numpy as np
    return np.add(x, y).tolist()

client.deploy('add', add, 'Adds two numbers x and y')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\haupinzd\AppData\Local\Programs\Python\Python36\lib\site-packages\tabpy_client\client.py", line 328, in deploy
    self._service.add_endpoint(_Endpoint(**obj))
  File "C:\Users\haupinzd\AppData\Local\Programs\Python\Python36\lib\site-packages\tabpy_client\rest_client.py", line 219, in add_endpoint
    endpoint.to_json()
  File "C:\Users\haupinzd\AppData\Local\Programs\Python\Python36\lib\site-packages\tabpy_client\rest.py", line 172, in POST
    return self.network_wrapper.POST(self.endpoint + url, data, timeout)
  File "C:\Users\haupinzd\AppData\Local\Programs\Python\Python36\lib\site-packages\tabpy_client\rest.py", line 108, in POST
    self.raise_error(response)
  File "C:\Users\haupinzd\AppData\Local\Programs\Python\Python36\lib\site-packages\tabpy_client\rest.py", line 63, in raise_error
    raise ResponseError(response)
**tabpy_client.rest.ResponseError: (400) Error when changing TabPy state: 'TABPY_STATE_PATH' {}**
`
Any ideas?

**Comment by haupinzd** [comment]
Running the server with startup.bat seems to work.
