### ISSUE TITLE
An error Occurred while communicating with the Predictive Service

### ISSUE THREAD

**Issue by scrocker** [tableau/TabPy#15]
i'm using a very simple script that works on the tabpy server through ipython server console but when I add this to tableau I get the following error

Here is what's in tableau:
SCRIPT_REAL(
"return tabpy.query('subtract2', _arg1, _arg2)['response']",SUM([6]),SUM([5])
)

Here is the Error Block
Error processing script
Error when POST /evaluate: Traceback
Traceback (most recent call last):
File "tabpy.py", line 467, in post
result = yield self.call_subprocess(function_to_evaluate, arguments)
File "C:\Users\SCrocker\Anaconda\envs\Tableau-Python-Server\lib\site-packages\tornado\gen.py", line 1008, in run
value = future.result()
File "C:\Users\SCrocker\Anaconda\envs\Tableau-Python-Server\lib\site-packages\tornado\concurrent.py", line 232, in result
raise_exc_info(self._exc_info)
File "C:\Users\SCrocker\Anaconda\envs\Tableau-Python-Server\lib\site-packages\tornado\gen.py", line 1014, in run
yielded = self.gen.throw(*exc_info)
File "tabpy.py", line 488, in call_subprocess
ret = yield future
File "C:\Users\SCrocker\Anaconda\envs\Tableau-Python-Server\lib\site-packages\tornado\gen.py", line 1008, in run
value = future.result()
File "C:\Users\SCrocker\Anaconda\envs\Tableau-Python-Server\lib\site-packages\concurrent\futures\_base.py", line 400, in result
return self.__get_result()
File "C:\Users\SCrocker\Anaconda\envs\Tableau-Python-Server\lib\site-packages\concurrent\futures\_base.py", line 359, in __get_result
reraise(self._exception, self._traceback)
File "C:\Users\SCrocker\Anaconda\envs\Tableau-Python-Server\lib\site-packages\concurrent\futures\_compat.py", line 107, in reraise
exec('raise exc_type, exc_value, traceback', {}, locals_)
File "C:\Users\SCrocker\Anaconda\envs\Tableau-Python-Server\lib\site-packages\concurrent\futures\thread.py", line 61, in run
result = self.fn(*self.args, **self.kwargs)
File "<string>", line 2, in _user_script
KeyError: 'response'
Error type : KeyError
Error message : 'response'

**Comment by BBeran** [comment]
Hi,
Would you be able to share the function definition and a screenshot of your command line console where TabPy writes? That would help identify the problem. 

My guess based on what's provided here is that subtract function has an issue. This might be because Tableau passes all the data as vectors/arrays and you might be treating them like scalars in your function. Here is a working example.

https://github.com/tableau/TabPy/blob/master/client.md#deploying-a-function

Thank you,

Bora

**Comment by BBeran** [comment]
Hi,
Here is an example subtract function that you can deploy and call from Tableau that won't cause any errors as it can deal with data being passed as arrays.

def subtract(x,y):
	import numpy as np
	return np.subtract(x,y).tolist()

Please reactivate if the issue persists with this function as well.

Thank you,

Bora
