### ISSUE TITLE
Trouble with BigIP

### ISSUE THREAD

**Issue by itsAftab** [tableau/TabPy#178]
I have modified the config file to listen to the machine name where TabPy is installed

```
TABPY_QUERY_OBJECT_PATH = /tmp/query_objects
TABPY_PORT = 9004
TABPY_STATE_PATH = ./
TABPY_BIND_IP = abcdef.myhost.com
TABPY_LOG_LEVEL = INFO
```

As long as TABPY_BIND_IP is the machine name, TabPy starts fine.
Since TabPy is installed on the Tableau server and the server is a cluster of 4 nodes, I need to change TABPY_BIND_IP to BigIP which in my case is: tab-s.myhost.com

```
TABPY_QUERY_OBJECT_PATH = /tmp/query_objects
TABPY_PORT = 9004
TABPY_STATE_PATH = ./
TABPY_BIND_IP = tab-s.myhost.com
TABPY_LOG_LEVEL = INFO
```

When I do that I get the following error: 

C:\Program Files\TabPy>startup.cmd
Starting TabPy server...

```
C:\Program Files\TabPy>startup.cmd
Starting TabPy server...

Initializing TabPy...
Done initializing TabPy.
Traceback (most recent call last):
  File "tabpy.py", line 991, in <module>
    main()
  File "tabpy.py", line 975, in main
    application.listen(settings['port'], address=settings['bind_ip'])
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\tornado\web.py", line 2042, in listen
    server.listen(port, address)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\tornado\tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\tornado\netutil.py", line 122, in bind_sockets
    0, flags)):
  File "C:\Program Files (x86)\Python37-32\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed`
```

**Comment by nmannheimer** [comment]
Hi @itsAftab, have you confirmed that Tableau Server does not function correctly with TabPy when it is set to the original IP? This config parameter can also be commented out to not bind the IP.

**Comment by itsAftab** [comment]
@nmannheimer no it didn't but the issue is resolved by adding server's IP address pointing to BigIP in server's .host-file

```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
# localhost name resolution is handled within DNS itself.
12.34.56.78		tableau.myhost.com
```
