### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.      Failed to start TabPy server.

### ISSUE THREAD

**Issue by lorenmspeer** [tableau/TabPy#297]
Running window 10
Looks like the install went ok, but when starting TabPy server it cannot connect Here's the text it gives me:

Starting TabPy server...

Traceback (most recent call last):
  File "tabpy-server\tabpy_server\tabpy.py", line 2, in <module>
    from tabpy_server.app.app import TabPyApp
  File "C:\Users\lspeer\Desktop\TabPy-master\tabpy-server\tabpy_server\app\app.py", line 12, in <module>
    from tabpy_server.app.util import (
  File "C:\Users\lspeer\Desktop\TabPy-master\tabpy-server\tabpy_server\app\util.py", line 6, in <module>
    from OpenSSL import crypto
  File "C:\Users\lspeer\AppData\Local\Continuum\anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\lspeer\AppData\Local\Continuum\anaconda3\lib\site-packages\OpenSSL\crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "C:\Users\lspeer\AppData\Local\Continuum\anaconda3\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Users\lspeer\AppData\Local\Continuum\anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: The specified procedure could not be found.
     Failed to start TabPy server.

**Comment by 0golovatyi** [comment]
@lorenmspeer What version of TabPy and Python are you using?

**Comment by lorenmspeer** [comment]
Python 3.7.0
TabPy 0.4.1
Anaconda 4.5.11

**Comment by 0golovatyi** [comment]
@lorenmspeer My guess is cryptography module can't be loaded which causes the failure. There are 2 things you may want to try:
1. Try to reinstall it with `pip uninstall cryptography` and then `pip install cryptography`, or
2. Add OpenSSL binary folder to your PATH.
