### ISSUE TITLE
/tmp/query_object issue when installing Tabpy using startup.cmd

### ISSUE THREAD

**Issue by sivakora** [tableau/TabPy#336]
**Environment information:**
 - OS: [Windows, Linux, Mac] and version
 - Python version: [e.g. 3.7.3]

**Describe the issue**
I face below issue when i try to start tabpy server

Python 3.7.3
Installing any missing dependencies...
    success
    Check "C:\Users\u1188773.US02P01\TabPy"\tabpy-server\install.log for details.
Parsing parameters...
Starting TabPy server...

2019-08-16,14:44:29 [DEBUG] (app.py:app:179): Parameter port set to "9004" from config file
2019-08-16,14:44:29 [DEBUG] (app.py:app:192): Parameter server_version set to "0.7" from default value
2019-08-16,14:44:29 [DEBUG] (app.py:app:192): Parameter evaluate_timeout set to "30" from default value
2019-08-16,14:44:29 [DEBUG] (app.py:app:179): Parameter upload_dir set to "/tmp/query_objects" from config file
Traceback (most recent call last):
  File "tabpy-server\tabpy_server\tabpy.py", line 10, in <module>
    main()
  File "tabpy-server\tabpy_server\tabpy.py", line 5, in main
    app = TabPyApp()
  File "C:\Users\TabPy\tabpy-server\tabpy_server\app\app.py", line 56, in __init__
    self._parse_config(config_file)
  File "C:\Users\TabPy\tabpy-server\tabpy_server\app\app.py", line 220, in _parse_config
    os.makedirs(self.settings[SettingsParameters.UploadDir])
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/tmp/query_objects'
     Failed to start TabPy server.

**To Reproduce**
Just followed the documentation from github

**Expected behavior**
Should have started the Tabpy on port 9004

**Comment by 0golovatyi** [comment]
@sivakora In the environment information you said it is TabPy v0.4.1, but log shows it is TabPy 0.7. Which exact version are you using? v0.7 is pre-release at the moment is being tested BTW.

**Comment by sivakora** [comment]
@0golovatyi : Sorry that wrong version i mentioned before. It is from TabPy 0.7 which i pulled from Git. My Bad, let me try downloading the old version and then try installing

**Comment by sivakora** [comment]
Tried 0.4 but i still face same issue.

**Comment by 0golovatyi** [comment]
@sivakora Can you try to create `c:\tmp\query_objects` folder and run tabpy again? Seems like it is not able to create the folder by itself on startup.

If you find you don't have enough permissions to create the folder you'll need to change `TABPY_QUERY_OBJECT_PATH` setting in config file.

**Comment by sivakora** [comment]
created \tmp\query_objects in C drive and that worked like a charm. Thanks @0golovatyi
