### ISSUE TITLE
Tabpy Starting issue

### ISSUE THREAD

**Issue by hello4usharath** [tableau/TabPy#368]
**Environment information:**
 - OS: Windows    Version : window server 2016
 - Python version: [e.g. 3.6.5] : 3.8.0
 - TabPy release: [e.g. 0.4.1] : "0.8.9"

**Describe the issue**

Followed below installation steps and trying to  start the tabpy 

To install TabPy on to an environment pip needs to be installed and updated first:

python -m pip install --upgrade pip

Now TabPy can be install as a package:

pip install tabpy

Starting TabPy

To start TabPy with default setting run the following command:

tabpy

And Getting below error 

C:\Windows\system32>tabpy
2019-11-28,02:22:47 [DEBUG] (app.py:app:214): Parameter port set to "9004" from default value
2019-11-28,02:22:47 [DEBUG] (app.py:app:214): Parameter server_version set to "0.8.9" from default value
2019-11-28,02:22:47 [DEBUG] (app.py:app:214): Parameter evaluate_timeout set to "30" from default value
2019-11-28,02:22:47 [DEBUG] (app.py:app:214): Parameter upload_dir set to "d:\tableau\python\lib\site-packages\tabpy\tmp\query_objects" from default value
2019-11-28,02:22:47 [DEBUG] (app.py:app:214): Parameter transfer_protocol set to "http" from default value
2019-11-28,02:22:47 [DEBUG] (app.py:app:220): Parameter certificate_file is not set
2019-11-28,02:22:47 [DEBUG] (app.py:app:220): Parameter key_file is not set
2019-11-28,02:22:47 [DEBUG] (app.py:app:214): Parameter state_file_path set to "d:\tableau\python\lib\site-packages\tabpy\tabpy_server" from default value
2019-11-28,02:22:47 [INFO] (app.py:app:280): Loading state from state file D:\Tableau\python\Lib\site-packages\tabpy\tabpy_server\state.ini
2019-11-28,02:22:47 [DEBUG] (app.py:app:214): Parameter static_path set to "./" from default value
2019-11-28,02:22:47 [DEBUG] (app.py:app:292): Static pages folder set to "C:\Windows\system32"
2019-11-28,02:22:47 [DEBUG] (app.py:app:220): Parameter TABPY_PWD_FILE is not set
2019-11-28,02:22:47 [INFO] (app.py:app:310): Password file is not specified: Authentication is not enabled
2019-11-28,02:22:47 [DEBUG] (app.py:app:214): Parameter log_request_context set to "false" from default value
2019-11-28,02:22:47 [INFO] (app.py:app:327): Call context logging is disabled
2019-11-28,02:22:47 [DEBUG] (app.py:app:214): Parameter max_request_size_in_mb set to "100" from default value
2019-11-28,02:22:47 [INFO] (app.py:app:110): Initializing TabPy...
2019-11-28,02:22:47 [DEBUG] (proactor_events.py:proactor_events:623): Using proactor: IocpProactor
2019-11-28,02:22:47 [INFO] (callbacks.py:callbacks:42): Initializing TabPy Server...
2019-11-28,02:22:47 [DEBUG] (state.py:state:147): Collected endpoints: {}
2019-11-28,02:22:47 [INFO] (app.py:app:113): Done initializing TabPy.
2019-11-28,02:22:47 [INFO] (app.py:app:67): Setting max request size to 104857600 bytes
2019-11-28,02:22:47 [INFO] (callbacks.py:callbacks:62): Initializing models...
2019-11-28,02:22:47 [DEBUG] (state.py:state:147): Collected endpoints: {}
Traceback (most recent call last):
  File "d:\tableau\python\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\tableau\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Tableau\python\Scripts\tabpy.exe\__main__.py", line 7, in <module>
  File "d:\tableau\python\lib\site-packages\tabpy\tabpy.py", line 32, in main
    app.run()
  File "d:\tableau\python\lib\site-packages\tabpy\tabpy_server\app\app.py", line 86, in run
    application.listen(
  File "d:\tableau\python\lib\site-packages\tornado\web.py", line 2042, in listen
    server.listen(port, address)
  File "d:\tableau\python\lib\site-packages\tornado\tcpserver.py", line 144, in listen
    self.add_sockets(sockets)
  File "d:\tableau\python\lib\site-packages\tornado\tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "d:\tableau\python\lib\site-packages\tornado\netutil.py", line 268, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "d:\tableau\python\lib\site-packages\tornado\platform\asyncio.py", line 79, in add_handler
    self.asyncio_loop.add_reader(
  File "d:\tableau\python\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

**Expected behavior**
tabpy should be up and running

**Screenshots**
![image](https://user-images.githubusercontent.com/22592994/69799813-fd27e300-11f9-11ea-804e-1c54066d9825.png)

**Comment by 0golovatyi** [comment]
@hello4usharath TabPy doesn't work with Python 3.8 - not all the packages TabPy depends on are ready yet. Recommended is Python 3.6 or 3.7.

**Comment by hello4usharath** [comment]
Hi Oleksanr,

How does tabpy work on tableau server and desktop?

Thanks
Sharath

**Comment by 0golovatyi** [comment]
@hello4usharath TabPy doesn't need to be running on the same machine which runs Tableau Desktop/Server if this is what you are asking. Here's the documentation page for how to use TabPy with Tableau - https://github.com/tableau/TabPy/blob/master/docs/TableauConfiguration.md.

**Comment by hello4usharath** [comment]
Getting below error while connecting from desktop  to tabpy (which in
windows server) using IP address and port 9004
External service server is busy or connection configuration is incorrect
(check connection type and other parameters)

**Comment by 0golovatyi** [comment]
Couple of things to check to narrow down what may cause the issue:
1. On the machine where TabPy is running (the machine you use to configure external service connection) confirm with logs it is up and listening to port 9004. 
2. From the machine, you are trying to connect to TabPy confirm you can reach TabPy machine (e.g. if you can successfully ping it).

**Comment by 0golovatyi** [comment]
@hello4usharath Are you still experiencing the issue?

**Comment by hello4usharath** [comment]
Yes, not able to connect tabpy server from my local system.

**Comment by hello4usharath** [comment]
From the machine, you are trying to connect to TabPy confirm you can reach TabPy machine (e.g. if you can successfully ping it). ... am able ping the server

**Comment by hello4usharath** [comment]
On the machine where TabPy is running (the machine you use to configure external service connection) confirm with logs it is up and listening to port 9004. -- its up and running

**Comment by 0golovatyi** [comment]
Okay, so the machine where TabPy is running can be reached from the machine where you run Tableau, also TabPy started successfully and listening to port 9004. In that case, it is possible you need to configure firewall settings to allow in/out connections for the machine/port.

**Comment by 0golovatyi** [comment]
@hello4usharath Do you have any updates?
