### ISSUE TITLE
Coveralls is not working - GITHUB_TOKEN not set

### ISSUE THREAD

**Issue by johng42** [tableau/TabPy#453]
**Environment information:**
 -github pipeline

**Describe the issue**
 ======================= 108 passed in 252.45s (0:04:12) ========================
Running on Github Actions but GITHUB_TOKEN is not set. Add "env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" to your step config.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/coveralls/cli.py", line 63, in main
    service_name=options['--service'])
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/coveralls/api.py", line 52, in __init__
    name, job, number, pr = self.load_config_from_ci_environment()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/coveralls/api.py", line 137, in load_config_from_ci_environment
    name, job, number, pr = self.load_config_from_github()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/coveralls/api.py", line 98, in load_config_from_github
    'Running on Github Actions but GITHUB_TOKEN is not set. '
coveralls.exception.CoverallsException: Running on Github Actions but GITHUB_TOKEN is not set. Add "env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" to your step config.
##[error]Process completed with exit code 1.

**To Reproduce**
use the web UI to make a trivial change that will not alter code coverage (https://github.com/tableau/TabPy/pull/451/checks?check_run_id=1098790538)
wait for coverage report

**Expected behavior**
no error

**Additional context**

**Comment by 0golovatyi** [comment]
I believe it was a fluke and the issue seems to be gone for now.
