### ISSUE TITLE
After tabpy installation error: configparser.DuplicateOptionError: While reading from '<dict>': option 'socks_proxy' in section 'DEFAULT' already exists

### ISSUE THREAD

**Issue by demekSR** [tableau/TabPy#525]
**Environment information:**
 - OS: SUSE Linux Enterprise Server 12 SP5"
 - Python version: python 3.8.12  (also python 3.8.1 and python 3.9.9)
 - TabPy release: 2.4.0 (also 2.3.1)

**Describe the issue**
After installation tabpy in accrodance with  https://tableau.github.io/TabPy/docs/server-install.html, when I run tabpy I am getting error:

 ```
 /infa/mgmt/pythons/python-3.8.12/bin> ./tabpy
Traceback (most recent call last):
  File "./tabpy", line 8, in <module>
    sys.exit(main())
  File "/infa/mgmt/pythons/python-3.8.12/lib/python3.8/site-packages/tabpy/tabpy.py", line 43, in main
    app = TabPyApp(config)
  File "/infa/mgmt/pythons/python-3.8.12/lib/python3.8/site-packages/tabpy/tabpy_server/app/app.py", line 76, in __init__
    self._parse_config(config_file)
  File "/infa/mgmt/pythons/python-3.8.12/lib/python3.8/site-packages/tabpy/tabpy_server/app/app.py", line 243, in _parse_config
    parser = configparser.ConfigParser(os.environ)
  File "/infa/mgmt/pythons/python-3.8.12/lib/python3.8/configparser.py", line 639, in __init__
    self._read_defaults(defaults)
  File "/infa/mgmt/pythons/python-3.8.12/lib/python3.8/configparser.py", line 1219, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/infa/mgmt/pythons/python-3.8.12/lib/python3.8/configparser.py", line 752, in read_dict
    raise DuplicateOptionError(section, key, source)
configparser.DuplicateOptionError: While reading from '<dict>': option 'socks_proxy' in section 'DEFAULT' already exists
```

**To Reproduce**

OpenSSl installation:

```
wget https://www.openssl.org/source/openssl-1.0.2o.tar.gz
 
./config --prefix=/infa/mgmt/pythons/openssl --openssldir=/infa/mgmt/pythons/openssl
make 
make install
```

Python installation:

```
 LDFLAGS="${LDFLAGS} -Wl,-rpath=/infa/mgmt/pythons/openssl/lib" ./configure --prefix=/infa/mgmt/pythons/python-3.8.12 --with-ensurepip=install --with-openssl=/infa/mgmt/pythons/openssl/
 make
 make test
 make install 
```
 
Tabpy installation:
`/infa/mgmt/pythons/python-3.8.12/bin/pip3.8 install tabpy
`
Run tabpy:

```
./tabpy
 
or 

./tabpy --config file.conf   
```

file.conf exactly the same like example: https://tableau.github.io/TabPy/docs/server-config.html#configuration-file-example

**Expected behavior**

Running tabpy wihtout error.

**Comment by nmannheimer** [comment]
@demekSR is this still an issue?

**Comment by demekSR** [comment]
Running command `unset socks_proxy` resolved the issue.
