### ISSUE TITLE
Heroku model deployments: os.isfile(path_to_pickle) returns true, but client.deploy(...) returns FileNotFoundError

### ISSUE THREAD

**Issue by Tor-Saxberg** [tableau/TabPy#603]
**Environment information:**
 - OS: [Windows, Linux, Mac] and version: Mac
 - Python version: [e.g. 3.6.5]: 3.11
 - TabPy release: [e.g. 0.4.1]: 2.6.0

**Describe the issue**
I have Tabpy running on a Heroku server, but no models are deployed on launch. I tried to deploy a model like this:
heroku run python3
>>> from tabpy.tabpy_tools.client import Client
>>> client = Client('https://tabpy-learning-agency.herokuapp.com/')
>>> client.set_credentials('learningagency','LAPass')
>>> def anova(_arg1, _arg2, *_argN):
...
>>> client.deploy('anova', anova, 'computes anova  p-value between several groups')

But this returns the below error message:

Overwriting existing file "/app/tabpy/tabpy_server/staging/endpoints/anova/1" when saving query object
Error with server response. code=500; text={"message": "error adding endpoint", "info": "FileNotFoundError : [Errno 2] No such file or directory: '/app/tabpy/tabpy_server/staging/endpoints/anova/1'"}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/tabpy/tabpy_tools/client.py", line 244, in deploy
    self._service.add_endpoint(Endpoint(**obj))
  File "/app/tabpy/tabpy_tools/rest_client.py", line 203, in add_endpoint
    return self.service_client.POST("endpoints", endpoint.to_json())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tabpy/tabpy_tools/rest.py", line 199, in POST
    return self.network_wrapper.POST(self.endpoint + url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/tabpy/tabpy_tools/rest.py", line 110, in POST
    self.raise_error(response)
  File "/app/tabpy/tabpy_tools/rest.py", line 62, in raise_error
    raise ResponseError(response)
tabpy.tabpy_tools.rest.ResponseError: (500) error adding endpoint FileNotFoundError : [Errno 2] No such file or directory: '/app/tabpy/tabpy_server/staging/endpoints/anova/1'

**Expected behavior**
The model would be deployed, show as deployed in https://xxx.herokuapp.com/, and function properly in Tableau Cloud.

**Additional context**
I also ran this for context:
>>> os.isfile('/app/tabpy/tabpy_server/staging/endpoints/anova/1/pickle_archive')
which returns: True

**Comment by Tor-Saxberg** [comment]
I found [this comment](https://stackoverflow.com/questions/67609679/tabpy-function-deployment-fails-on-docker-running-tabpy) on stackoverflow: 
"You can only deploy functions directly from Tabpy server. remote deployment is not possible."
But I also found that [Feature Request: Ability to remotely publish code #64](https://github.com/tableau/TabPy/issues/64) was closed as "completed."
 
I'm not sure how I would use Tabpy + Heroku if there was no way to use even the [predeployed functions](https://tableau.github.io/TabPy/docs/tabpy-tools.html#predeployed-functions) , so is there another way to deploy models?

**Comment by Tor-Saxberg** [comment]
I tried to just copy the entire 'tabpy/tabpy_server/staging/' directory like this:
'cp -r /opt/homebrew/lib/python3.10/site-packages/tabpy/tabpy_server/staging/endpoints tabpy/tabpy_server/staging/endpoints' , but that gives the following error (after pushing):
```
>>> from tabpy.tabpy_tools.client import Client
>>> client = Client('https://xxx.herokuapp.com/')
>>> client.set_credentials('xxx','xxx')
>>> def anova(_arg1, _arg2, *_argN):
...
>>> client.deploy('anova', anova, 'computes anova  p-value between several groups', override=True)
Overwriting existing file "/app/tabpy/tabpy_server/staging/endpoints/anova/1" when saving query object
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/tabpy/tabpy_tools/client.py", line 248, in deploy
    self._wait_for_endpoint_deployment(obj["name"], obj["version"])
  File "/app/tabpy/tabpy_tools/client.py", line 361, in _wait_for_endpoint_deployment
    raise RuntimeError(f'LoadFailed: {ep["last_error"]}')
RuntimeError: LoadFailed: Load failed: code() argument 13 must be str, not int

Also, I noticed that `endpoints/anova/1/` was not the latest version among the `endpoints/anova/` directories, which suggests that the `get_endpoints` method in the `Client` class in `tabpy/tabpy_tools/Client.py` is not reading it correctly or something.
