### ISSUE TITLE
Missing dependencies: numpy

### ISSUE THREAD

**Issue by VathsalaAchar** [tableau/TabPy#7]
I was trying to play around with the examples in the tabpy server and client but had an issue while using the add endpoint even after deploying it.

I tried the following:

> curl -X POST http://localhost:9004/evaluate \
    -d '{"data": {"_arg1":1, "_arg2":2},
         "script": "return tabpy.query(\"add\", x=_arg1, y=_arg2)[\"response\"]"}'

This was the error I got:

```
 info Error when POST /evaluate: Traceback
 Traceback (most recent call last):
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/tabpy_server/tabpy.py", line 468, in post
    result = yield self.call_subprocess(function_to_evaluate, arguments)
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/tabpy_server/tabpy.py", line 489, in call_subprocess
    ret = yield future
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/concurrent/futures/_base.py", line 400, in result
    return self.__get_result()
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/concurrent/futures/_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "/home/vathsala/anaconda2/envs/Tableau-Python-Server/lib/python2.7/site-packages/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<string>", line 2, in _user_script
KeyError: 'response'
```

When I removed `response` and tried

> curl -X POST http://localhost:9004/evaluate     -d '{"data": {"_arg1":1, "_arg2":2},
         "script": "return tabpy.query(\"add\", x=_arg1, y=_arg2)"}'

I got the error telling me numpy was missing. 

I installed numpy and all was well, but maybe the documentation needs updating, as well as have the server return better error messages?

**Comment by heavyhorse** [comment]
can you show the full stack trace error? 

also make sure you do `pip install ./tabpy-client` and `pip install ./tabpy-server`
I think the client is a dependency on the server

**Comment by VathsalaAchar** [comment]
I did all of that before I started and I have posted the stack trace above. And numpy is included in Anaconda but not in the environment created so any library will need to be in the requirements.

To prove my point I'm just following the steps as in the [documentation:](https://github.com/tableau/TabPy/blob/master/server.md#manual-installation)

Create the environment

`conda create --name Tableau-Python-Server-again python=2.7`

Before installing any requirement

```
(Tableau-Python-Server-again) > pip freeze
pbr==1.10.0
six==1.10.0
stevedore==1.14.0
virtualenv-clone==0.2.6
```

Following the steps in the documentation to install as asked:

```
pip install -r ./tabpy-server/requirements.txt
pip install ./tabpy-client
pip install ./tabpy-server
```

Once that is done and I `pip freeze` I get

```
awscli==1.6.2
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
bcdoc==0.12.2
botocore==0.73.0
certifi==2016.9.26
cloudpickle==0.2.1
colorama==0.2.5
decorator==4.0.10
docutils==0.12
functools32==3.2.3.post2
futures==2.2.0
genson==0.2.0
jmespath==0.5.0
jsonschema==2.5.1
pbr==1.10.0
pyasn1==0.1.9
python-dateutil==2.6.0
requests==2.3.0
rsa==3.1.2
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.10.0
stevedore==1.14.0
tabpy-client==0.1
tabpy-server==0.1
tornado==4.3
Tornado-JSON==1.2.0
virtualenv-clone==0.2.6
```

I had to manually take care of installing numpy, scikit-learn etc. to fix the error I got above. 

However if you create an environment like so

`conda create --name Tableau-Python-Server anaconda python=2.7` 

it will download all the packages that come with Anaconda, which is the reason I suggested that the documentation might need changing.

**Comment by BBeran** [comment]
I updated the manual install instructions. Thanks for reporting!
https://github.com/tableau/TabPy/commit/eac486d384de433441a14cc3ce6ed8cbd53e6998
